### ISSUE TITLE
QLabel Pixmap update Bug

### ISSUE THREAD

**Issue by MyraBaba** [githubuser0xFFFF/Qt-Advanced-Stylesheets#13]
Hi,
@githubuser0xFFFF 
I connected my video thread through signal slot and updating the label pixmap .

When I use Qt-Advanced-StyleSheet its stopping the update frame and over and over writing the boxes with black frame.

I I disable the Qt-Advanced-StyleSheet its working many hour without any problem ?
Qt 6.4.2
I attached the screen shot and I am updating the lable like this:
```

if (stream_id == 1) {

        ui->label_src_1->clear();
        ui->label_src_1->setPixmap(ASM::cvMatToQPixmap(frame));
    } else if (stream_id == 2) {

        ui->label_src_2->clear();
        ui->label_src_2->setPixmap(ASM::cvMatToQPixmap(frame));
    }
    qApp->processEvents();
```

here the screen with Qt-Advanced-StyleSheet  and without:

What makes the difference and causing the error ?

**Comment by githubuser0xFFFF** [comment]
I don't think, that this is related to the advanced style sheet library.

**Comment by MyraBaba** [comment]
@githubuser0xFFFF  you right I re-compiled all and all good now.

Best
