### ISSUE TITLE
Why not make it a plugin (svg part)?

### ISSUE THREAD

**Issue by RC1844** [githubuser0xFFFF/Qt-Advanced-Stylesheets#14]
We can make a new svg plugin to replace the original iconengines and imageformats plugins, so that we can keep using QIcon code without having to go through loadThemeAwareSvgIcon to create QIcon.
We can also inherit the QSvgRenderer and get a pointer to the QSvgTinyDocument from the d_ptr of the QSvgRenderer. By manipulating the members of the QSvgTinyDocument through some spoofing, changing the color will be easy.

**Comment by githubuser0xFFFF** [comment]
Good idea - that sounds nice. Please provide a pull request so that I can review it and we can discuss this further.

**Comment by RC1844** [comment]
@githubuser0xFFFF I did make a Dome, but it was modified on the QT plugin. I don't think it can be submitted as a PR

**Comment by githubuser0xFFFF** [comment]
Ok, then take your time to create a pull request and I will close this issue for now.
