### ISSUE TITLE
Qt 6 support ?

### ISSUE THREAD

**Issue by fxdeniz** [githubuser0xFFFF/Qt-Advanced-Stylesheets#5]
Hi, thanks for the awesome project.

Do you consider adding Qt 6 support ?

Currently, it does not compile for Qt 6. Because, code contains deprecated function calls.
Compiler gives errors such as, `'class QString' has no member named 'midRef'`.

**Comment by githubuser0xFFFF** [comment]
The new release 1.0.4 added Qt6 support
