### ISSUE TITLE
bulid warning

### ISSUE THREAD

**Issue by thewaterislo** [githubuser0xFFFF/Qt-Advanced-Stylesheets#9]
“Install Prefix not set” what is the problem？And how to solve？qt 5.12.12

**Comment by githubuser0xFFFF** [comment]
Only a warning - just ignore.

**Comment by thewaterislo** [comment]
but when i run it, just exit,nothing happened。cant build in windows？

**Comment by githubuser0xFFFF** [comment]
Then there is something wrong on your side and you need to find out what - the warning is not the problem.

**Comment by thewaterislo** [comment]
i did it! read the .pro carefully，i knew how it works finally. thank you for your reply ;)
